[phases.setup]
nixpkgs = ["gcc", "g++", "openjdk", "python3"]

[phases.install]
cmds = ["npm install --cache /tmp/.npm-cache"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"
